### PR TITLE
hello_part: remove `main-proc.rs`

### PR DESCRIPTION
**Pull request by emilengler**
This commit removes the `main-proc.rs` file from the repository, as it is an orphan and not used by anything.

### CODE REVIEW

**Comment by dadada** [comment]
I was wondering about that. Did the proc-macro thingy ever have acutal code or was it just a concept?

**Comment by emilengler** [comment]
> I was wondering about that. Did the proc-macro thingy ever have acutal code or was it just a concept?

@Steav005

**Comment by wucke13** [comment]
It did work to some degree, but its not yet finished. I would expect that this comes to life in one to two months.

**Review by Steav005 — APPROVED** [review]
This file should be re-added with the proc macro feature

**Pull request merged**
