### PR TITLE
core: fix cgroup test

### PR DESCRIPTION
**Pull request by emilengler**

### CODE REVIEW

**Comment by emilengler** [comment]
@dadada how do you execute the tests?

**Comment by dadada** [comment]
> @dadada how do you execute the tests?

`cargo test`

**Comment by dadada** [comment]
```
---- cgroup::tests::import_root stdout ----
thread 'cgroup::tests::import_root' panicked at 'assertion failed: !path.exists()', core/src/cgroup.rs:278:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- cgroup::tests::new_root stdout ----
thread 'cgroup::tests::new_root' panicked at 'assertion failed: !path.exists()', core/src/cgroup.rs:266:9

---- cgroup::tests::mv stdout ----
thread 'cgroup::tests::mv' panicked at 'called `Result::unwrap()` on an `Err` value: File exists (os error 17)', core/src/cgroup.rs:312:43

---- cgroup::tests::get_pids stdout ----
thread 'cgroup::tests::get_pids' panicked at 'assertion failed: cg1.get_pids().unwrap().is_empty()', core/src/cgroup.rs:329:9

---- cgroup::tests::frozen stdout ----
thread 'cgroup::tests::frozen' panicked at 'called `Result::unwrap()` on an `Err` value: Device or resource busy (os error 16)', core/src/cgroup.rs:393:17

---- cgroup::tests::populated stdout ----
thread 'cgroup::tests::populated' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', core/src/cgroup.rs:366:17

---- cgroup::tests::new stdout ----
thread 'cgroup::tests::new' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', core/src/cgroup.rs:300:18

```

**Comment by emilengler** [comment]
> > @dadada how do you execute the tests?
> 
> `cargo test`

It does not work that way. You have to do `cargo test -- --test-threads=1` and execute it as root with adding to this to `.cargo/config.toml`:
```
[target.x86_64-unknown-linux-gnu]
runner = 'sudo -E'
```

It is a hack, but it is documented inside the source code.

**Comment by emilengler** [comment]
Because the cgroup test use the FS as a shared state `--test-threads=1` and require root privileges.

**Comment by dadada** [comment]
Maybe could isolate tests better from each other? Separate hypervisor instances should already have sepratate cgroups. Maybe we could override the cgroup name for each test?

**Comment by dadada** [comment]
Tests are passing with `--test-threads=1`. You don't need sudo if you are running the tests in an app.slice.

**Review by dadada — APPROVED** [review]

**Comment by dadada** [comment]
https://github.com/aeronautical-informatics/apex-linux/issues/33

**Pull request merged**
